-- Thrift Star Supabase Schema Definition (V2 - Professional Listing Standards)

-- Drop existing tables and types to recreate schema cleanly
DROP TABLE IF EXISTS public.messages CASCADE;
DROP TABLE IF EXISTS public.swap_proposals CASCADE;
DROP TABLE IF EXISTS public.items CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

DROP TYPE IF EXISTS item_status CASCADE;
DROP TYPE IF EXISTS item_condition CASCADE;
DROP TYPE IF EXISTS proposal_status CASCADE;

-- 1. Users Table (Standalone for MVP mock data simplicity)
CREATE TABLE public.users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    rating NUMERIC DEFAULT 0,
    stripe_customer_id TEXT,
    paypal_account TEXT, -- User's default paypal email
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Items Table
CREATE TYPE item_status AS ENUM ('Available', 'In Negotiation', 'Swapped');
CREATE TYPE item_condition AS ENUM ('New', 'Gently Used', 'Used', 'Very Worn');

CREATE TABLE public.items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID REFERENCES public.users(id) NOT NULL,
    
    -- Core Listing Fields
    photos TEXT[] NOT NULL, -- Array of image URLs
    listing_title TEXT NOT NULL,
    brand TEXT NOT NULL,
    category TEXT, -- e.g., 'Tops', 'Outerwear', 'Sneakers'
    size TEXT NOT NULL,
    condition item_condition DEFAULT 'Used',
    color TEXT,
    description TEXT,
    
    -- Measurements (Crucial for engagement)
    measurements JSONB DEFAULT '{}'::jsonb, -- e.g. {"pit_to_pit": 22, "length": 28, "inseam": 32}
    
    -- Financials & Metadata
    price NUMERIC NOT NULL,
    retail_price NUMERIC, -- Original purchase price
    item_model_id TEXT,
    listing_tags TEXT[], -- Up to 10 hashtags
    
    -- Logistics & Sales Mechanics
    shipping_method TEXT DEFAULT 'Standard',
    shipping_cost NUMERIC DEFAULT 0.00,
    accepts_offers BOOLEAN DEFAULT true,
    
    -- Status
    status item_status DEFAULT 'Available',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Swap Proposals (Negotiations) Table
CREATE TYPE proposal_status AS ENUM ('Action Required', 'Countered', 'Accepted', 'Declined', 'Completed');

CREATE TABLE public.swap_proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_proposer_id UUID REFERENCES public.users(id) NOT NULL,
    original_receiver_id UUID REFERENCES public.users(id) NOT NULL,
    item_wanted_id BIGINT REFERENCES public.items(id) NOT NULL,
    item_offered_id BIGINT REFERENCES public.items(id) NOT NULL,
    cash_added NUMERIC DEFAULT 0,
    action_with_id UUID REFERENCES public.users(id) NOT NULL,
    status proposal_status DEFAULT 'Action Required',
    braintree_txn_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Messages Table
CREATE TABLE public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id BIGINT REFERENCES public.swap_proposals(id) ON DELETE CASCADE,
    sender_id UUID REFERENCES public.users(id) NOT NULL,
    message_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create RLS (Row Level Security) Policies
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.swap_proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read data
CREATE POLICY "Users are viewable by everyone" ON public.users FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON public.users FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Items are viewable by everyone" ON public.items FOR SELECT USING (true);
CREATE POLICY "Users can update items" ON public.items FOR UPDATE USING (auth.uid() = owner_id);
-- Allow users to insert their own items
CREATE POLICY "Users can insert their own items" ON public.items FOR INSERT WITH CHECK (auth.uid() = owner_id);

-- Allow users to view negotiations they are part of
CREATE POLICY "Users can view their own negotiations" ON public.swap_proposals FOR SELECT USING (auth.uid() = original_proposer_id OR auth.uid() = original_receiver_id);
CREATE POLICY "Users can create swap proposals" ON public.swap_proposals FOR INSERT WITH CHECK (auth.uid() = original_proposer_id);
CREATE POLICY "Users can update their swap proposals" ON public.swap_proposals FOR UPDATE USING (auth.uid() = original_proposer_id OR auth.uid() = original_receiver_id);

-- Messages RLS
CREATE POLICY "Users can insert messages" ON public.messages FOR INSERT WITH CHECK (auth.uid() = sender_id);
CREATE POLICY "Users can view messages" ON public.messages FOR SELECT USING (true);
