-- V3 E-Commerce Schema Update (Run this once to upgrade your database!)

-- 1. Add 'Sold' to item_status ENUM
ALTER TYPE item_status ADD VALUE IF NOT EXISTS 'Sold';

-- 2. Modify Swap Proposals to allow "Cash Only / Make Offer" without an item
ALTER TABLE public.swap_proposals ALTER COLUMN item_offered_id DROP NOT NULL;

-- 3. Shopping Cart Table
CREATE TABLE IF NOT EXISTS public.cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) NOT NULL,
    item_id BIGINT REFERENCES public.items(id) NOT NULL UNIQUE
);
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their cart" ON public.cart_items FOR ALL USING (auth.uid() = user_id);

-- 4. Direct Orders Table (For Buy Now & Cart Checkouts)
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id UUID REFERENCES public.users(id) NOT NULL,
    seller_id UUID REFERENCES public.users(id) NOT NULL,
    item_id BIGINT REFERENCES public.items(id) NOT NULL,
    amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'Paid',
    braintree_txn_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Buyers and sellers can view orders" ON public.orders FOR SELECT USING (auth.uid() = buyer_id OR auth.uid() = seller_id);
CREATE POLICY "Buyers can insert orders" ON public.orders FOR INSERT WITH CHECK (auth.uid() = buyer_id);
